name: cake_shop
description: "A system dedicated to productive families, specifically those who work in cake making."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.3.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.7
  cupertino_icons: ^1.0.6
  auto_route: ^8.1.3
  flex_color_scheme: ^7.3.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.5
  dartz: ^0.10.1
  get_it: ^7.7.0
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1
  iconsax: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  auto_route_generator: ^8.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/


